version: "3"

includes:
  utils: ../Taskfile.dist.yaml

silent: true

tasks:
  setup-all:
    desc: Install vscode, extensions and custom settings
    cmds:
      - task: install
      - task: extensions:install
      - task: links

  install:
    desc: Install vscode - code editor
    vars:
      KEY_URL: "https://packages.microsoft.com/keys/microsoft.asc"
      KEY_FILE: "/usr/share/keyrings/vscode.gpg"
      SRC_URL: "https://packages.microsoft.com/repos/code"
      SRC_FILE: "/etc/apt/sources.list.d/vscode.list"
    cmds:
      - wget -qO - {{.KEY_URL}} | gpg --dearmor | sudo tee {{.KEY_FILE}} > /dev/null
      - echo "deb [arch={{ARCH}} signed-by={{.KEY_FILE}}] {{.SRC_URL}} stable main" |
        sudo tee {{.SRC_FILE}} > /dev/null
      - task: utils:apt:install-code
    status: [command -v code]

  extensions:install:
    desc: Install useful vscode extensions
    cmds:
      - code --install-extension alphabotsec.vscode-eclipse-keybindings
      - code --install-extension bierner.emojisense
      - code --install-extension brunnerh.insert-unicode
      - code --install-extension chrmarti.regex
      - code --install-extension dhruv.maven-dependency-explorer
      - code --install-extension eamodio.gitlens
      - code --install-extension editorconfig.editorconfig
      - code --install-extension formulahendry.code-runner
      - code --install-extension golang.go
      - code --install-extension humao.rest-client
      - code --install-extension ms-azuretools.vscode-docker
      - code --install-extension ms-vscode.cmake-tools
      - code --install-extension ms-vscode.cpptools
      - code --install-extension ms-vscode.cpptools-extension-pack
      - code --install-extension ms-vscode.cpptools-themes
      - code --install-extension ms-vscode-remote.remote-containers
      - code --install-extension pkief.material-icon-theme
      - code --install-extension redhat.java
      - code --install-extension redhat.vscode-yaml
      - code --install-extension sonarsource.sonarlint-vscode
      - code --install-extension twxs.cmake
      - code --install-extension visualstudioexptteam.intellicode-api-usage-examples
      - code --install-extension visualstudioexptteam.vscodeintellicode
      - code --install-extension vscjava.vscode-java-debug
      - code --install-extension vscjava.vscode-java-dependency
      - code --install-extension vscjava.vscode-java-pack
      - code --install-extension vscjava.vscode-java-test
      - code --install-extension vscjava.vscode-maven
      - code --install-extension vscode-icons-team.vscode-icons
      - code --install-extension zhuangtongfa.material-theme
    preconditions:
      - sh: command -v code
        msg: command [code] is not available - install vscode and include [code] in your $PATH

  extensions:list:
    desc: List installed vscode extensions
    cmd: code --list-extensions | sort
    preconditions:
      - sh: command -v code
        msg: command [code] is not available - install vscode and include [code] in your $PATH

  links:
    desc: Create symlinks for vscode configuration files
    vars:
      SOURCE_PATH: "{{.TASKFILE_DIR}}"
      TARGET_PATH: "{{.HOME}}/.config/Code/User"
    sources: [config/*.json]
    cmds:
      - for: sources
        cmd: ln -sf {{joinPath .SOURCE_PATH .ITEM}} {{joinPath .TARGET_PATH (base .ITEM)}}
