#!/usr/bin/bash

# ======================================================================================================================
# Creates a swapfile `/swapfile` 3GB in size and loads it in `/etc/fstab`
# A backup of `/etc/fstab` is created before adding `/swapfile` to it
#
# Author: kyrex23
# Date:   23/10/2022
# ======================================================================================================================

set -euo pipefail

# ----------------------------------------------------------------------------------------------------------------------

SWAPSIZE="3G"

SWAPFILE="/swapfile"

FSTAB="/etc/fstab"
FSTAB_BKP="$FSTAB.bkp"

FSTAB_LINES=(
	"# $SWAPFILE generated by ${0##*/} (created by: Kyrex)"
	"$SWAPFILE\tnone\tswap\tsw\t0\t0"
)

# ----------------------------------------------------------------------------------------------------------------------

# Create the file used as swap area if it is not already created
echo "Creating the file '$SWAPFILE'..."
if [ ! -f $SWAPFILE ]; then
	sudo fallocate --length $SWAPSIZE $SWAPFILE && echo "✅ File '$SWAPFILE' created sucessfully"
	sudo chmod 600 $SWAPFILE                    && echo "✅ File permissions changed to: rw-------"
	sudo mkswap $SWAPFILE >/dev/null            && echo "✅ Swap area created in: '$SWAPFILE'"
else
	echo "⚠️  File: '$SWAPFILE' already exists"
fi
echo


# Enable the swapfile if necessary
echo "Enabling swapfile..."
if ! swapon --show | grep --quiet ^$SWAPFILE; then
	sudo swapon $SWAPFILE                       && echo "✅ '$SWAPFILE' enabled"
else
	echo "⚠️  '$SWAPFILE' is already enabled"
fi
echo


# Load /swapfile in /etc/fstab if is not already added
echo "Loading '$SWAPFILE' in $FSTAB..."
if  ! grep --quiet ^$SWAPFILE $FSTAB; then
	sudo cp $FSTAB $FSTAB_BKP                   && echo "✅ Backup of $FSTAB created at: $FSTAB_BKP"
	# Add lines to /etc/fstab
	for line in "${FSTAB_LINES[@]}"; do echo -e $line | sudo tee --append $FSTAB > /dev/null; done
else echo "⚠️  $SWAPFILE was already added in $FSTAB"
fi
echo

echo "✅ Completed successfully"
