version: "3"

includes:
  dist: ../Taskfile.dist.yaml

tasks:
  docker:install:
    desc: Install docker - application container engine
    vars:
      KEY_URL: "https://download.docker.com/linux/ubuntu/gpg"
      KEY_FILE: "/usr/share/keyrings/docker.gpg"
      SRC_URL: "https://download.docker.com/linux/ubuntu"
      SRC_FILE: "/etc/apt/sources.list.d/docker.list"
      DISTRIBUTION_NAME:
        sh: lsb_release -cs
    cmds:
      - wget -qO - {{.KEY_URL}} | gpg --dearmor | sudo tee {{.KEY_FILE}} > /dev/null
      - echo "deb [arch={{ARCH}} signed-by={{.KEY_FILE}}] {{.SRC_URL}} {{.DISTRIBUTION_NAME}} stable" |
        sudo tee {{.SRC_FILE}} > /dev/null
      - task: dist:apt:install-docker-ce
      - task: dist:apt:install-docker-ce-cli
      - task: dist:apt:install-containerd.io
      - task: dist:apt:install-docker-compose-plugin
      - sudo usermod -aG docker $USER
      - echo "🟢 User [$USER] has been added to [docker] group (logout is required)"
    status: [command -v docker]
