version: "3"

includes:
  utils: ./Taskfile.dist.yaml

silent: true

tasks:
  calibre:install:
    desc: Install calibre - ebook manager
    cmd: wget -qO - https://download.calibre-ebook.com/linux-installer.sh | bash
    status: [command -v calibre]

  google-chrome:install:
    desc: Install google-chrome - web browser
    vars:
      KEY_URL: "https://dl.google.com/linux/linux_signing_key.pub"
      KEY_FILE: "/usr/share/keyrings/google-chrome.gpg"
      SRC_URL: "https://dl.google.com/linux/chrome/deb"
      SRC_FILE: "/etc/apt/sources.list.d/google-chrome.list"
    cmds:
      - wget -qO - {{.KEY_URL}} | gpg --dearmor | sudo tee {{.KEY_FILE}} > /dev/null
      - echo "deb [arch={{ARCH}} signed-by={{.KEY_FILE}}] {{.SRC_URL}} stable main" | sudo tee {{.SRC_FILE}} > /dev/null
      - task: utils:apt:install-google-chrome-stable
    status: [command -v google-chrome]

  spotify:install:
    desc: Install spotify - streaming music client
    vars:
      KEY_URL: "https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg"
      KEY_FILE: "/usr/share/keyrings/spotify.gpg"
      SRC_URL: "http://repository.spotify.com"
      SRC_FILE: "/etc/apt/sources.list.d/spotify.list"
    cmds:
      - wget -qO - {{.KEY_URL}} | gpg --dearmor | sudo tee {{.KEY_FILE}} > /dev/null
      - echo "deb [arch={{ARCH}} signed-by={{.KEY_FILE}}] {{.SRC_URL}} stable non-free" |
        sudo tee {{.SRC_FILE}} > /dev/null
      - task: utils:apt:install-spotify-client
    status: [command -v spotify]
